# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid.xci
# IP: The module: 'sine_mid' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_mid'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid.xci
# IP: The module: 'sine_mid' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sine_mid'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
