# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.cache/wt [current_project]
set_property parent.project_path /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:kc705:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid.xci
set_property used_in_implementation false [get_files -all /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid.dcp]
set_property is_locked true [get_files /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top sine_mid -part xc7k325tffg900-2 -mode out_of_context
rename_ref -prefix_all sine_mid_
write_checkpoint -noxdef sine_mid.dcp
catch { report_utilization -file sine_mid_utilization_synth.rpt -pb sine_mid_utilization_synth.pb }
if { [catch {
  file copy -force /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.runs/sine_mid_synth_1/sine_mid.dcp /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.ip_user_files/ip/sine_mid]} {
  catch { 
    file copy -force /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid_stub.v /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.ip_user_files/ip/sine_mid
  }
}

if {[file isdir /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.ip_user_files/ip/sine_mid]} {
  catch { 
    file copy -force /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/ip/sine_mid/sine_mid_stub.vhdl /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.ip_user_files/ip/sine_mid
  }
}
