# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.cache/wt [current_project]
set_property parent.project_path /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:kc705:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.runs/sine_low_synth_1/sine_low.dcp
set_property used_in_implementation false [get_files /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.runs/sine_low_synth_1/sine_low.dcp]
add_files -quiet /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.runs/sine_high_synth_1/sine_high.dcp
set_property used_in_implementation false [get_files /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.runs/sine_high_synth_1/sine_high.dcp]
add_files -quiet /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.runs/sine_mid_synth_1/sine_mid.dcp
set_property used_in_implementation false [get_files /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.runs/sine_mid_synth_1/sine_mid.dcp]
read_vhdl -library xil_defaultlib {
  /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/imports/lab1/sinegen.vhd
  /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/imports/lab1/fsm.vhd
  /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/imports/lab1/debounce.vhd
  /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/sources_1/imports/lab1/sinegen_demo.vhd
}
read_xdc /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/constrs_1/imports/lab1/sinegen_demo_kc705.xdc
set_property used_in_implementation false [get_files /home/l329869/vhdl_tutorial/debug_tutorial/test_projects/lab1_prj/lab1_prj.srcs/constrs_1/imports/lab1/sinegen_demo_kc705.xdc]

synth_design -top sinegen_demo -part xc7k325tffg900-2 -flatten_hierarchy none
write_checkpoint -noxdef sinegen_demo.dcp
catch { report_utilization -file sinegen_demo_utilization_synth.rpt -pb sinegen_demo_utilization_synth.pb }
